In [1]:
print("HELLO , AI!")

HELLO , AI!

In [2]:
import pandas as pd
df = pd.read_excel(r"D:\archive\futuretools_all_3539_tools.csv")
df.head()

ValueError: Excel file format cannot be determined, you must specify an engine manually.

In [3]:
import pandas as pd

df = pd.read_csv(r"D:\archive\futuretools_all_3539_tools.csv")

df.head()

,Tool Name,Short Description,Internal Link,External Link,Long Description,Pricing,Tags
0,AI inTime,A tool to track and analyze time spent across ...,https://www.futuretools.io/tools/ai-intime,https://futuretools.link/aiintime-com,AI in Time is an intelligent time management p...,Paid,Productivity
1,Awaz.ai,A call to create multilingual voice assistants...,https://www.futuretools.io/tools/awaz-ai,https://futuretools.link/awaz-ai,Awaz AI is a voice-enabled Conversational AI e...,Paid + Free Trial,Marketing
2,Bit Flows,A tool automate WordPress processes by connect...,https://www.futuretools.io/tools/bit-flows,https://futuretools.link/bit-flows-com,Bit Flows is a powerful WordPress automation p...,Paid + Free Trial,Productivity
3,Tile,A tool to generate API integration code.,https://www.futuretools.io/tools/tile,https://futuretools.link/tile-dev,Tile.dev is a developer tool that streamlines ...,Freemium,Generative Code
4,Keepmind,"A personal memory assistant to capture, organi...",https://www.futuretools.io/tools/keepmind,https://futuretools.link/keepmind-ai,KeepMind AI is a personal memory assistant tha...,Paid + Free Trial,Productivity

In [4]:
import numpy as np

In [5]:
df.shape()

TypeError: 'tuple' object is not callable

In [6]:
df.shape

(3494, 7)

In [7]:
df.isnull().sum()

Tool Name            0
Short Description    1
Internal Link        0
External Link        0
Long Description     0
Pricing              0
Tags                 0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [10]:
df['tag'] = df['Short Description'] + df['Internal Link'] + df['External Link'] + df['Long Description'] + df['Pricing'] + df['Tags']

In [11]:
df.head()

,Tool Name,Short Description,Internal Link,External Link,Long Description,Pricing,Tags,tag
0,AI inTime,A tool to track and analyze time spent across ...,https://www.futuretools.io/tools/ai-intime,https://futuretools.link/aiintime-com,AI in Time is an intelligent time management p...,Paid,Productivity,A tool to track and analyze time spent across ...
1,Awaz.ai,A call to create multilingual voice assistants...,https://www.futuretools.io/tools/awaz-ai,https://futuretools.link/awaz-ai,Awaz AI is a voice-enabled Conversational AI e...,Paid + Free Trial,Marketing,A call to create multilingual voice assistants...
2,Bit Flows,A tool automate WordPress processes by connect...,https://www.futuretools.io/tools/bit-flows,https://futuretools.link/bit-flows-com,Bit Flows is a powerful WordPress automation p...,Paid + Free Trial,Productivity,A tool automate WordPress processes by connect...
3,Tile,A tool to generate API integration code.,https://www.futuretools.io/tools/tile,https://futuretools.link/tile-dev,Tile.dev is a developer tool that streamlines ...,Freemium,Generative Code,A tool to generate API integration code.https:...
4,Keepmind,"A personal memory assistant to capture, organi...",https://www.futuretools.io/tools/keepmind,https://futuretools.link/keepmind-ai,KeepMind AI is a personal memory assistant tha...,Paid + Free Trial,Productivity,"A personal memory assistant to capture, organi..."

In [13]:
new_df = df[['Tool Name', 'tag']]

In [14]:
new_df

        Tool Name                                                tag
0       AI inTime  A tool to track and analyze time spent across ...
1         Awaz.ai  A call to create multilingual voice assistants...
2       Bit Flows  A tool automate WordPress processes by connect...
3            Tile  A tool to generate API integration code.https:...
4        Keepmind  A personal memory assistant to capture, organi...
...           ...                                                ...
3489        Coqui  Generative AI Voiceshttps://www.futuretools.io...
3490      Murf.ai  AI realistic text-to-speech voice generatorhtt...
3491      Play.ht  AI realistic text-to-speech voice generatorhtt...
3492       Poised  Real-time feedback on your speaking, using AIh...
3493  Resemble.ai  AI realistic text-to-speech voice generator - ...

[3494 rows x 2 columns]

In [15]:
new_df['tag'][0]

"A tool to track and analyze time spent across applications.https://www.futuretools.io/tools/ai-intimehttps://futuretools.link/aiintime-comAI in Time is an intelligent time management platform that uses artificial intelligence to automatically track, categorize, and analyze how you spend your time across different applications and activities. The tool eliminates manual time logging by leveraging AI algorithms to recognize patterns in your workflow, intelligently assign time entries to projects, and provide data-driven insights about your productivity habits. Whether you're a freelancer tracking billable hours, a project manager optimizing team resources, or a professional seeking better work-life balance, AI in Time helps you visualize where your time goes, identify inefficiencies, and make more informed decisions about your schedule through predictive analytics and personalized recommendations that adapt to your unique working style.PaidProductivity"

In [18]:
pip install nltk

Requirement already satisfied: nltk in c:\users\srijn\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: click in c:\users\srijn\anaconda3\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\srijn\anaconda3\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\srijn\anaconda3\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\srijn\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\srijn\anaconda3\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [1]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words = 'english' )

In [2]:
import nltk

In [3]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [4]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import string

ps = PorterStemmer()

def preprocess(text):
    text = text.lower()
    words = text.split()

    words = [
        ps.stem(word)
        for word in words
        if word not in stopwords.words('english')
        and word not in string.punctuation
    ]

In [6]:
new_df = new_df['tag'].apply(stem)

NameError: name 'new_df' is not defined

In [7]:
import pandas as pd

df = pd.read_csv(r"D:\archive\futuretools_all_3539_tools.csv")

df.head()

,Tool Name,Short Description,Internal Link,External Link,Long Description,Pricing,Tags
0,AI inTime,A tool to track and analyze time spent across ...,https://www.futuretools.io/tools/ai-intime,https://futuretools.link/aiintime-com,AI in Time is an intelligent time management p...,Paid,Productivity
1,Awaz.ai,A call to create multilingual voice assistants...,https://www.futuretools.io/tools/awaz-ai,https://futuretools.link/awaz-ai,Awaz AI is a voice-enabled Conversational AI e...,Paid + Free Trial,Marketing
2,Bit Flows,A tool automate WordPress processes by connect...,https://www.futuretools.io/tools/bit-flows,https://futuretools.link/bit-flows-com,Bit Flows is a powerful WordPress automation p...,Paid + Free Trial,Productivity
3,Tile,A tool to generate API integration code.,https://www.futuretools.io/tools/tile,https://futuretools.link/tile-dev,Tile.dev is a developer tool that streamlines ...,Freemium,Generative Code
4,Keepmind,"A personal memory assistant to capture, organi...",https://www.futuretools.io/tools/keepmind,https://futuretools.link/keepmind-ai,KeepMind AI is a personal memory assistant tha...,Paid + Free Trial,Productivity

In [8]:
new_df = df[['Tool Name', 'tag']]

KeyError: "['tag'] not in index"

In [9]:
df['tag'] = df['Short Description'] + df['Internal Link'] + df['External Link'] + df['Long Description'] + df['Pricing'] + df['Tags']

In [10]:
new_df = df[['Tool Name', 'tag']]

In [11]:
new_df

        Tool Name                                                tag
0       AI inTime  A tool to track and analyze time spent across ...
1         Awaz.ai  A call to create multilingual voice assistants...
2       Bit Flows  A tool automate WordPress processes by connect...
3            Tile  A tool to generate API integration code.https:...
4        Keepmind  A personal memory assistant to capture, organi...
...           ...                                                ...
3489        Coqui  Generative AI Voiceshttps://www.futuretools.io...
3490      Murf.ai  AI realistic text-to-speech voice generatorhtt...
3491      Play.ht  AI realistic text-to-speech voice generatorhtt...
3492       Poised  Real-time feedback on your speaking, using AIh...
3493  Resemble.ai  AI realistic text-to-speech voice generator - ...

[3494 rows x 2 columns]

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words = 'english' )

In [13]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import string

ps = PorterStemmer()

def preprocess(text):
    text = text.lower()
    words = text.split()

    words = [
        ps.stem(word)
        for word in words
        if word not in stopwords.words('english')
        and word not in string.punctuation
    ]

In [16]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [17]:
new_df['tag'] = new_df['tag'].apply(stem)

AttributeError: 'float' object has no attribute 'split'

In [18]:
vectors = cv.fit_transform(new_df['tag']).toarray()

ValueError: np.nan is an invalid document, expected byte or unicode string.

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
cv = CountVectorizer(max_features=5000, stop_words='english')

In [21]:
vectors = cv.fit_transform(new_df['tag']).toarray()

ValueError: np.nan is an invalid document, expected byte or unicode string.

In [22]:
new_df['tag'].isnull().sum()

np.int64(1)

In [23]:
new_df = new_df.dropna(subset=['tag'])

In [24]:
new_df['tag'].isnull().sum()

np.int64(0)

In [25]:
import re

new_df['tag'] = new_df['tag'].fillna('')

new_df['tag'] = new_df['tag'].apply(
    lambda x: re.sub(r'http\S+|www\S+', '', x)
)

C:\Users\srijn\AppData\Local\Temp\ipykernel_14220\3163497305.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag'] = new_df['tag'].fillna('')
C:\Users\srijn\AppData\Local\Temp\ipykernel_14220\3163497305.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag'] = new_df['tag'].apply(

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')

vectors = cv.fit_transform(new_df['tag']).toarray()

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words='english'
)

vectors = tfidf.fit_transform(new_df['tag']).toarray()

In [28]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

In [29]:
vectors.shape

(3493, 5000)

In [30]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

In [31]:
similarity.shape

(3493, 3493)

In [32]:
def recommend(tool_name):
    tool_name = tool_name.strip()

    if tool_name not in new_df['Tool Name'].values:
        print("Tool not found!")
        return

    idx = new_df[new_df['Tool Name'] == tool_name].index[0]

    distances = similarity[idx]

    tool_list = sorted(
        list(enumerate(distances)),
        key=lambda x: x[1],
        reverse=True
    )[1:6]

    print(f"\nRecommendations for {tool_name}:\n")

    for i in tool_list:
        print(new_df.iloc[i[0]]['Tool Name'])

In [33]:
recommend("Murf.ai")

Recommendations for Murf.ai:

Resemble.ai
Acoust
AiSofiya
11.ai
Gotalk.ai

In [34]:
new_df = new_df.reset_index(drop=True)

In [35]:
def recommend(tool_name):
    tool_name = tool_name.strip()

    matches = new_df[new_df['Tool Name'].str.lower() == tool_name.lower()]

    if matches.empty:
        print("Tool not found!")
        return

    idx = matches.index[0]

    distances = similarity[idx]

    recommended = sorted(
        list(enumerate(distances)),
        key=lambda x: x[1],
        reverse=True
    )[1:6]

    print(f"\nTop recommendations for '{tool_name}':\n")

    for i, score in recommended:
        print(f"{new_df.iloc[i]['Tool Name']} ({score:.3f})")

In [36]:
recommend("Murf.ai")

Top recommendations for 'Murf.ai':

Play.ht (0.404)
Voxify (0.366)
Resemble.ai (0.360)
Gotalk.ai (0.332)
Verbatik (0.317)

In [37]:
recommend("ChatGPT")

Tool not found!

In [38]:
import pickle

pickle.dump(new_df, open('tools.pkl', 'wb'))
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [1]:
import pickle

tools = pickle.load(open("tools.pkl", "rb"))

print(type(tools))
print(tools.columns.tolist())
print(tools.head())

similarity = pickle.load(open("similarity.pkl", "rb"))

print(type(similarity))
print(similarity.shape)

<class 'pandas.core.frame.DataFrame'>
['Tool Name', 'tag']
   Tool Name                                                tag
0  AI inTime  A tool to track and analyze time spent across ...
1    Awaz.ai  A call to create multilingual voice assistants...
2  Bit Flows  A tool automate WordPress processes by connect...
3       Tile  A tool to generate API integration code. is a ...
4   Keepmind  A personal memory assistant to capture, organi...
<class 'numpy.ndarray'>
(3493, 3493)